[package]
name = "aoc20"
version = "0.1.0"
authors = ["ike <isaac.lewis@signfracturecare.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
itertools = "0.9.0"
regex = "1.1.0"
